-- Partner-agnostic fulfillment orchestration for the Unwrapt MVP.
-- The browser may read an owner's records through RLS. All state changes are
-- performed by the fulfillment-router Edge Function with the service role.

create table public.fulfillment_orders (
  id uuid primary key default gen_random_uuid(),
  scheduled_gift_id uuid not null unique references public.scheduled_gifts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references public.recipients(id) on delete cascade,
  route text not null check (route in ('exact_gift', 'recipient_choice', 'retailer_handoff', 'concierge')),
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  status text not null default 'draft' check (status in (
    'draft', 'awaiting_sender', 'awaiting_recipient', 'recipient_selected',
    'ready_for_partner', 'submitted_to_partner', 'shipped', 'delivered',
    'exception', 'cancelled'
  )),
  provider text not null default 'unassigned',
  partner_status text,
  external_order_id text,
  partner_checkout_url text,
  tracking_url text,
  choice_token_hash text unique,
  choice_expires_at timestamptz,
  exception_reason text,
  metadata jsonb not null default '{}'::jsonb,
  approved_at timestamptz,
  recipient_selected_at timestamptz,
  submitted_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.fulfillment_options (
  id uuid primary key default gen_random_uuid(),
  fulfillment_order_id uuid not null references public.fulfillment_orders(id) on delete cascade,
  product_id text references public.products(id) on delete set null,
  title text not null,
  description text,
  image_url text,
  price numeric(10, 2),
  currency text not null default 'USD',
  product_url text,
  provider text not null default 'shopify',
  provider_product_id text,
  provider_variant_id text,
  rank smallint not null default 0,
  is_selected boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (fulfillment_order_id, product_id)
);

create table public.fulfillment_events (
  id bigint generated by default as identity primary key,
  fulfillment_order_id uuid not null references public.fulfillment_orders(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text,
  actor_type text not null check (actor_type in ('sender', 'recipient', 'system', 'partner', 'operator')),
  actor_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index fulfillment_orders_user_created_idx
  on public.fulfillment_orders(user_id, created_at desc);
create index fulfillment_orders_status_idx
  on public.fulfillment_orders(status) where status not in ('delivered', 'cancelled');
create index fulfillment_options_order_rank_idx
  on public.fulfillment_options(fulfillment_order_id, rank);
create index fulfillment_events_order_created_idx
  on public.fulfillment_events(fulfillment_order_id, created_at);

create or replace function public.set_fulfillment_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger fulfillment_orders_updated_at
before update on public.fulfillment_orders
for each row execute function public.set_fulfillment_updated_at();

create trigger fulfillment_options_updated_at
before update on public.fulfillment_options
for each row execute function public.set_fulfillment_updated_at();

alter table public.fulfillment_orders enable row level security;
alter table public.fulfillment_options enable row level security;
alter table public.fulfillment_events enable row level security;

create policy "Owners can read fulfillment orders"
on public.fulfillment_orders for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Owners can read fulfillment options"
on public.fulfillment_options for select to authenticated
using (exists (
  select 1 from public.fulfillment_orders orders
  where orders.id = fulfillment_options.fulfillment_order_id
    and orders.user_id = (select auth.uid())
));

create policy "Owners can read fulfillment events"
on public.fulfillment_events for select to authenticated
using (exists (
  select 1 from public.fulfillment_orders orders
  where orders.id = fulfillment_events.fulfillment_order_id
    and orders.user_id = (select auth.uid())
));

revoke all on public.fulfillment_orders from anon, authenticated;
revoke all on public.fulfillment_options from anon, authenticated;
revoke all on public.fulfillment_events from anon, authenticated;
grant select on public.fulfillment_orders to authenticated;
grant select on public.fulfillment_options to authenticated;
grant select on public.fulfillment_events to authenticated;

comment on table public.fulfillment_orders is
  'Partner-agnostic routing and status record. Recipient access is only through a hashed, expiring token handled by the Edge Function.';
comment on column public.fulfillment_orders.metadata is
  'Non-sensitive provider and routing context only. Never store recipient addresses or raw choice tokens.';
